services:
  django:
    container_name: django
    build:
      context: ./backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./deploy/caddy.json:/etc/caddy/caddy.json:rw  # permite acceso desde Django
      
    environment:
      - CADDY_ADMIN=http://caddy:2019
    

  caddy:
    container_name: caddy
    build:
      context: ./deploy
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "2019:2019"
    depends_on:
      - django
